export const SAMPLE_ONE_REQUEST = 'SAMPLE_ONE_REQUEST';
export const SAMPLE_ONE_SUCCESS = 'SAMPLE_ONE_SUCCESS';
export const SAMPLE_ONE_FAILURE = 'SAMPLE_ONE_FAILURE';
export const ADD_SAMPLE_TWO = 'ADD_SAMPLE_TWO';
export const UPDATE_SAMPLE_TWO = 'UPDATE_SAMPLE_TWO';
export const DELETE_SAMPLE_TWO = 'DELETE_SAMPLE_TWO';
export const SAMPLE_THREE_ACTION = 'SAMPLE_THREE_ACTION';
